version: "3.7"
services:
  # Our "hello" service, this is our primary
  # service we request from via http://localhost
  hello:
    image: wyveo/nginx-php-fpm:php80
    restart: "no"
    volumes:
      - ./services/hello:/usr/share/nginx/html
      - ./services/hello/server/nginx.conf:/etc/nginx/nginx.conf
      - ./services/hello/server/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"